// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukxfcgediktwklgnnnsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVreGZjZ2VkaWt0d2tsZ25ubnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjE3NDIsImV4cCI6MjA1OTc5Nzc0Mn0.lyOgR5l1WApLyyf9kemx6Efpglv3jPgyV50mRniEzdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);